### PR TITLE
Update GitHub actions

### PR DESCRIPTION
**Pull request by digitaldogsbody**
## Purpose
Github Actions for Bracco are out of sync with most other DataCite repositories

## Approach
This PR removes some redundant actions and brings the triggers for building and deploying to Stage, Test, and Production in line with other DataCite repositories:

- Pushing to `main` (and, temporarily, also to `stage`) builds, tests and deploys to Staging
- Publishing a tagged release builds, tests and deploys to Test and Production

#### Open Questions and Pre-Merge TODOs

- [x] There is currently another action file that runs on Releases ([release.yml](https://github.com/datacite/bracco/blob/main/.github/workflows/release.yml)), but this is using the Docker setup and deploying via Terraform/mastino that I think is now redundant. Can we safely remove this file?
- [x] There are Cypress tests in the repo that aren't configured in either of the action files (e.g `consortium_admin` has a [prefixes.test.ts](https://github.com/datacite/bracco/blob/github-actions/cypress/integration/consortium_admin/prefixes.test.ts) file, but this is not called by the Cypress section in the action files. Should we tackle this by adding the missing tests to the actions files, or is it better to change the way the Cypress run happens to pick up all the tests automatically rather than enumerating them? (@svogt0511 your input here would be appreciated)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [x] Breaking change (fix or feature that would cause existing functionality to change) (**Possibly** if we remove the `releases.yml` file - see above)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by richardhallett** [comment]
I do not think it's nescessary to keep building stage branch as well as `main`, this will cause confusion with deployments. If we're now saying staging will be built from `main` then I think it's reasonable to just stop using the `stage` branch.

**Comment by digitaldogsbody** [comment]
I kept it looking at `stage` as a temporary thing because of the current differences between `stage` and `main`. However if we're happy that the new deploy process will be alright, then I can change that and we can just merge and delete `stage` immediately after this PR is merged.

**Review by richardhallett — APPROVED** [review]

**Comment by digitaldogsbody** [comment]
Ok, I have pushed a change to no longer trigger on pushes to `stage`.

Remaining things to be resolved:
1) The disparity in Cypress test files and what the runner actually uses - on further thought I think this should probably be spun out into a separate ticket as we might want to include it in our wider discussions about how we approach testing/github actions.
2) Whether `release.yml` can safely be removed?

**Review by jrhoads — APPROVED** [review]
These changes all look good.

I agree, if Vercel is the method of deployment/release, I do not think that updating terraform is necessary.  I defer to @richardhallett on that though.

**Comment by richardhallett** [comment]
Yes terraform doesn't handle vercel just AWS stuff, used to be for container deploys. You can remove it.
Lets handle cypress testing seperatly.

**Comment by digitaldogsbody** [comment]
I've removed the `release.yml` file and opened #577 for the Cypress tests

**Pull request merged**
