### PR TITLE
Fabrica improvements 1

### PR DESCRIPTION
**Pull request by svogt0511**
## Purpose

Implements [Fabrica Improvements, Feature 1](https://docs.google.com/document/d/1Tl6ctSaSG3487IMktlgfy8IZaMYVRTNzu5VObyqXCWY/edit#heading=h.ad09laaqdqwu): 'Create DOI From Any Page' as described in [Fabrica 4.0 (2022 improvements) Product Spec](https://docs.google.com/document/d/1Tl6ctSaSG3487IMktlgfy8IZaMYVRTNzu5VObyqXCWY/edit?usp=sharing) and [Fabrica 4.0 Improvements Technical Spec - 2022](https://docs.google.com/document/d/1dstFR8KIPR3oHPoN9Yk9Y_80xg_y_njsDcCNtV1sIl4/edit?usp=sharing).

Vercel deployment: https://bracco-di4k8mof2-datacite.vercel.app/

closes: datacite/datacite#1512

## Approach

Used the ember-bootstrap integration described [here](https://getbootstrap.com/docs/3.4/components/#btn-dropdowns-split) for this button making it conform to our styles with [local style overrides](https://github.com/datacite/bracco/pull/638/files#diff-f02862e584e50e884897d95a329262827eaf1c2af59ac1fbd052296e9e634fe9) as necessary

Updated [abilities/privilege calculation](https://github.com/datacite/bracco/pull/638/files#diff-a7e3154748c7a636a3a307bbfaae71c70646bcb49e458f00b8235cccb5aed9d1) as necessary to show or not show the button as described in the product spec.

Expanded [cypress test suite](https://github.com/datacite/bracco/pull/638/files#diff-01945b393e0192f3b785829f601161546c256259ef2b29ea0fe940a8f741b69f) to make sure that the button appears or does not appear as specified in the product spec. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [X] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by kjgarza** [comment]
@svogt0511 
> * Currently, clicking on the new Create DOI button doesn't do anything, you have to use the drop down menu. Perhaps the clicking on it could default to the DOI Form page?

I actually was debating myself about this before. One reason that I didn't include it was that such a component didn't exist. But I wonder, do you think it would be very complex @svogt0511 ?



> * When logged in to a repository through the staff account, the Create DOI button shows on each page. However, when logged in to a repository through a member account, it does not, the user has to log in as the repository itself. Should the members be able to also add DOIs when not explicitly logged in to their repository account, similar to the staff account?

No, this is not possible. Only client_Admins have rights to create dois. Not other accounts should.

**Review by bklaing2 — APPROVED** [review]
I like it, I think the new button makes a lot more sense!

**Comment by svogt0511** [comment]
> @svogt0511
> 
> > * Currently, clicking on the new Create DOI button doesn't do anything, you have to use the drop down menu. Perhaps the clicking on it could default to the DOI Form page?
> 
> I actually was debating myself about this before. One reason that I didn't include it was that such a component didn't exist. But I wonder, do you think it would be very complex @svogt0511 ?
> 
> > * When logged in to a repository through the staff account, the Create DOI button shows on each page. However, when logged in to a repository through a member account, it does not, the user has to log in as the repository itself. Should the members be able to also add DOIs when not explicitly logged in to their repository account, similar to the staff account?
> 
> No, this is not possible. Only client_Admins have rights to create dois. Not other accounts should.

I chose a new component button that works better and looks better. If you want to change things, let me know.  We can probably do something.  

I left the 'create doi' button in for staff_admin because that functionality is currently present.  If you want to change that we can.

I am merging this code, but will re-open this task if you think we need to.

**Comment by kjgarza** [comment]
I'm not sure if the changes are already deployed in branch but for context the functionality and look would be good to emulate the Front button . More comments  in https://app.frontapp.com/open/cnv_al3kb4l
image

**Pull request merged**
