### PR TITLE
send logged in user to settings

### PR DESCRIPTION
**Pull request by kjgarza**
## Purpose

send logged in user to settings
Consortium Lead, Consortium Orgs, Direct Members and Repositories should land on Settings tab when logging in to Fabrica.

closes: https://github.com/datacite/bracco/issues/467

## Approach
reverses https://github.com/datacite/bracco/issues/362 for consortium organisations

## Learning

In order to save new recording in polly one needs to change the mode to 

```
    mode: 'record',
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by mfenner** [comment]
@kjgarza please explain why you change the intentional redirection to the list of consortium organizations when consortium accounts log in. The reasoning was that this is what consortium accounts mostly do, manage consortium organizations.

**Comment by mfenner** [comment]
Also, the pull request is not addressing #467.

**Comment by kjgarza** [comment]
@MaryHirsch could you help us to confirm this?. I thought it was confirmed this behaviour was a bug

**Comment by mfenner** [comment]
@kjgarza this was not confirmed to be a bug. I said "Sound like a bug that needs investigating." and on further investigation was not a bug.

**Review by mfenner — APPROVED** [review]
LGTM

**Pull request merged**
