### PR TITLE
Add Service Provider integrations to repository software list

### PR DESCRIPTION
**Pull request by KellyStathis**
## Purpose

This is the same as https://github.com/datacite/bracco/pull/720 from a branch, rather than a fork.

#### Open Questions and Pre-Merge TODOs

Add entries to list in app/models/repository.js

Open Questions and Pre-Merge TODOs
- [ ] Testing required (I don't have Fabrica set up in a dev environment).
- [ ] Docs - update screenshot: https://support.datacite.org/docs/update-repository-settings#software

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by KellyStathis** [comment]
Oops, missed that there were other changes in the same file I needed to not overwrite. @svogt0511 I'll fix that, sorry!

**Comment by KellyStathis** [comment]
@svogt0511 Should be correct now, with the only changes being the softwareList values.

**Comment by KellyStathis** [comment]
@svogt0511 I wasn't sure whether to go ahead and merge this. Please let me know :)

**Comment by svogt0511** [comment]
> @svogt0511 I wasn't sure whether to go ahead and merge this. Please let me know :)

Looks good, but do the 'rebase and merge'

**Review by svogt0511 — APPROVED** [review]
Looks good but do 'rebase and merge' since things have changed since you created the branch.

**Pull request merged**
