### PR TITLE
Adding about page with version information

### PR DESCRIPTION
**Pull request by mfenner**
## Purpose
Show Fabrica version in new About page (and Ember Inspector) to make sure the user is using the expected version when there are issues. Uses [ember-cli-app-version](https://github.com/ember-cli/ember-cli-app-version).

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by mfenner** [comment]
Bildschirmfoto 2021-02-01 um 21 06 42

**Comment by svogt0511** [comment]
Looks good.  I like being able to just preview it.  from https://bracco-git-show-version.datacite.vercel.app/about. I also like that you can see the 'About' page whether or not you are logged in.

There seems to be a problem with the cookie banner.  It seems to have a mind of its own.  It is reappearing even after I have accepted the cookies and logged in.  For example, here I am, logged in, but the cookie is still reappearing when I go to a new page or refresh the current page.  

image

**Comment by mfenner** [comment]
@svogt0511 we should look into what domain we set the consent cookie for, so that the code works for branches other than dev and master deployed to a vercel.app domain. But that is not directly related to what the pull request is about.

**Review by svogt0511 — APPROVED** [review]
Looks good.

**Pull request merged**
