### PR TITLE
Fabrica improvements 3

### PR DESCRIPTION
**Pull request by bklaing2**
## Purpose

closes: https://github.com/datacite/datacite/issues/1514

## Approach
Added the new logo to the page header, and updated the background color of the right button div to correspond to the user's role

#### Open Questions and Pre-Merge TODOs
@kjgarza, could you please take a look at these questions. I have deployed these changes to Vercel for you to take a look at: https://bracco-9brtt4ykb-datacite.vercel.app/
- [ ] On some pages the new logo doesn't look great. For example on the [sign-in page](https://bracco-9brtt4ykb-datacite.vercel.app/sign-in) it is hard to see against the background image.
image

- [ ] When the background color of the navbar buttons is light blue, the text color when hovering over the buttons doesn't contrast very well and makes it hard to read.
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by svogt0511** [comment]
@bklaing2 - Regarding the logo issue.  Sometimes putting a box behind it with a slightly opaque background color can make something like that more readable.  Something to discuss with @kjgarza about the visual design.

**Comment by kjgarza** [comment]
@bklaing2 Check the Brand Guidelines https://datacite.org/assets/DataCite_Design_manual-version_1_0.pdf you can use the reverse of one of the style for link text

Screenshot 2022-10-20 at 09 20 41

**Review by svogt0511 — APPROVED** [review]
Looks good to me.  My only really minor comment is to balance out the padding on the home page to the right of 'sign in'.

Running this locally, the colors we talked about yesterday (when hovering over the navbar in the upper right) look ok with the dark background color and could have a little more contrast when hovering over the light background color.

Did you change the logo for the sign-in page?

Also, if you make changes please re-deploy to vercel.

As long as Kristian is ok with how things look I will approve this.

Thanks.  All very minor comments.

**Comment by bklaing2** [comment]
@kjgarza, I've made the changes that we discussed. Here's the new [Vercel build](https://bracco-dczzb0q3r-datacite.vercel.app/)
- The logo now doesn't show on pages with the the graphic background
- The new nav background colors only shows if the user is logged in as a member or consortium lead
- The button colors now contrast better with the new background colors

**Review by svogt0511 — APPROVED** [review]
Looks good to me!

**Pull request merged**
