### PR TITLE
feat: force all the dois updated with the form to become schema 4

### PR DESCRIPTION
**Pull request by kjgarza**
## Purpose
Forces all DOIs updated in the form to become schema 4. 

closes: https://github.com/datacite/bracco/issues/447

## Approach

All DOIs updated in the form will be transformed to schema 4. Independently of the state of the DOI (draft, registered, findable)

## Learning

Looking back at the form support messages it can be seen that the form has not support schema transformation on the past. See https://app.frontapp.com/open/msg_29opdsb from 2019 ,which is related to https://github.com/datacite/datacite/issues/654

This most likely due to the form modifying the metadata fields. The schema version is not a metadata field.

## Status
- [x] Ready for Review

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by richardhallett** [comment]
So what will happen in the scenario of older schema version with missing data, the form should fail to submit because it will be missing required fields right? and therefore once they fill it in, it will be valid schema 4?

**Comment by mfenner** [comment]
Can't review as I am on vacation.

**Comment by kjgarza** [comment]
its mostly and FYI @mfenner .

@richardhallett yeah, in that case, it will fail until they fill all the fields correctly.

**Comment by kjgarza** [comment]
unrelated test are failing because DOIs already exist (422) which doesn't make sense. This might be related to datacite/lupo#606. This needs be fixed to merge.

**Pull request merged**
