### PR TITLE
Feature client transfer

### PR DESCRIPTION
**Pull request by kjgarza**
## Purpose

Allows `staff admin` to transfer repositories

resolves: https://github.com/datacite/bracco/issues/404

## Approach

Adds a component to transfer repository.
It also renames the repository-transfer component as repository-dois-transfer to better fit its Purpose.

## Learning

Fabrica stays in cache for a long time sometimes.

## Status
- [x] Ready for Review

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by kjgarza** [comment]
as mentioned in the `purpose`, it just a refactor of the component to transfer dois:

> It also renames the `repository-transfer` component as `repository-dois-transfer` to better fit its purpose.

One component its for the transfer doi functionality (the old/refactored one) and the new one is for transferring repositories.

**Comment by mfenner** [comment]
Why not `repository-transfer` and `doi-transfer`. That is what the user sees in the UI.

**Comment by kjgarza** [comment]
`doi-transfer` already exists, remember? https://github.com/datacite/bracco/blob/master/app/components/doi-transfer.js that's for the transfer of a DOI. it's for a single doi.

`repository-dois-transfer` is the old component that transfers all the dois of a single repository.

`repository-dois-transfer` shows:
https://doi.datacite.org/repositories/rads.sch/transfer


while `repository-transfer` shows:
https://codepen.io/kjgarza/full/YzyNxLg

**Comment by mfenner** [comment]
@kjgarza thanks for clarifying that, this makes sense.

**Pull request merged**
