### PR TITLE
Tests covering all models

### PR DESCRIPTION
**Pull request by sarala**
I have created tests for all models which tests for existence of the models and computed values.

### CODE REVIEW

**Comment by sarala** [comment]
@mfenner, which ones would you like to see extended?

**Comment by mfenner** [comment]
@sarala nothing urgent, but some tests are more or less boilerplate code.

**Comment by sarala** [comment]
@mfenner, I mainly did two things:
1. tests for computed variables
2. test model exist (boilerplate code) where there are no computed variables. There is nothing else to test in those models. However, it had no impact on codeclimate coverage.

**Comment by mfenner** [comment]
One example would be the test for organization abilities. There are various user roles and various abilities.

**Comment by sarala** [comment]
I thought you do that in abilities unit tests rather than model.

**Pull request merged**
